LOCATION_DATA = [
    {
        "id": "1",
        "addressComponents": [
            {"long_name": "48", "short_name": "48", "types": ["street_number"]},
            {"long_name": "Pirrama Road", "short_name": "Pirrama Rd", "types": ["route"]},
            {"long_name": "Pyrmont", "short_name": "Pyrmont", "types": ["locality", "political"]},
            {"long_name": "City of Sydney", "short_name": "City of Sydney", "types": ["administrative_area_level_2", "political"]},
            {"long_name": "New South Wales", "short_name": "NSW", "types": ["administrative_area_level_1", "political"]},
            {"long_name": "Australia", "short_name": "AU", "types": ["country", "political"]},
            {"long_name": "2009", "short_name": "2009", "types": ["postal_code"]}
        ],
        "adrFormatAddress": "48 Pirrama Rd, Pyrmont NSW 2009, Australia",
        "formattedAddress": "48 Pirrama Rd, Pyrmont NSW 2009, Australia",
        "location": {"latitude": -33.866489, "longitude": 151.195698},
        "plusCode": "4RRH+JF Pyrmont, New South Wales",
        "shortFormattedAddress": "48 Pirrama Rd, Pyrmont NSW",
        "types": ["premise", "establishment"],
        "displayName": "Google Sydney",
        "googleMapsUri": "https://maps.google.com/?cid=10281119596374313554",
        "primaryType": "corporate_office",
        "primaryTypeDisplayName": "Corporate Office",
        "subDestinations": None,
        "rating": 4.5,
        "userRatingCount": 1500,
        "websiteUri": "https://about.google/locations/?region=australia&office=sydney",
        "parkingOptions": {"selfParkingAvailable": True, "valetParkingAvailable": False},
        "paymentOptions": None,
        "outdoorSeating": False,
        "reservable": False,
        "reviews": [
            {"authorAttribution": {"displayName": "John Doe"}, "text": "Amazing office with great views!", "rating": 5},
            {"authorAttribution": {"displayName": "Jane Smith"}, "text": "Impressive building and location.", "rating": 4}
        ]
    },
    {
        "id": "2",
        "addressComponents": [
            {"long_name": "Sydney Opera House", "short_name": "Sydney Opera House", "types": ["premise"]},
            {"long_name": "Bennelong Point", "short_name": "Bennelong Point", "types": ["route"]},
            {"long_name": "Sydney", "short_name": "Sydney", "types": ["locality", "political"]},
            {"long_name": "Council of the City of Sydney", "short_name": "Sydney", "types": ["administrative_area_level_2", "political"]},
            {"long_name": "New South Wales", "short_name": "NSW", "types": ["administrative_area_level_1", "political"]},
            {"long_name": "Australia", "short_name": "AU", "types": ["country", "political"]},
            {"long_name": "2000", "short_name": "2000", "types": ["postal_code"]}
        ],
        "adrFormatAddress": "Sydney Opera House, Bennelong Point, Sydney NSW 2000, Australia",
        "formattedAddress": "Sydney Opera House, Bennelong Point, Sydney NSW 2000, Australia",
        "location": {"latitude": -33.8567844, "longitude": 151.2152967},
        "plusCode": "4RRH+H3 Sydney, New South Wales",
        "shortFormattedAddress": "Sydney Opera House, Sydney NSW",
        "types": ["tourist_attraction", "point_of_interest", "establishment"],
        "displayName": "Sydney Opera House",
        "googleMapsUri": "https://maps.google.com/?cid=5037676569914146429",
        "primaryType": "tourist_attraction",
        "primaryTypeDisplayName": "Tourist Attraction",
        "subDestinations": None,
        "rating": 4.7,
        "userRatingCount": 81000,
        "websiteUri": "https://www.sydneyoperahouse.com/",
        "parkingOptions": {"selfParkingAvailable": True, "valetParkingAvailable": True},
        "paymentOptions": None,
        "outdoorSeating": True,
        "reservable": True,
        "reviews": None
    },
    {
        "id": "3",
        "addressComponents": [
            {"long_name": "1", "short_name": "1", "types": ["street_number"]},
            {"long_name": "Notts Avenue", "short_name": "Notts Ave", "types": ["route"]},
            {"long_name": "Bondi Beach", "short_name": "Bondi Beach", "types": ["locality", "political"]},
            {"long_name": "Waverley Council", "short_name": "Waverley", "types": ["administrative_area_level_2", "political"]},
            {"long_name": "New South Wales", "short_name": "NSW", "types": ["administrative_area_level_1", "political"]},
            {"long_name": "Australia", "short_name": "AU", "types": ["country", "political"]},
            {"long_name": "2026", "short_name": "2026", "types": ["postal_code"]}
        ],
        "adrFormatAddress": "1 Notts Ave, Bondi Beach NSW 2026, Australia",
        "formattedAddress": "1 Notts Ave, Bondi Beach NSW 2026, Australia",
        "location": {"latitude": -33.8914755, "longitude": 151.2766845},
        "plusCode": "4R6R+CF Bondi Beach, New South Wales",
        "shortFormattedAddress": "1 Notts Ave, Bondi Beach NSW",
        "types": ["natural_feature", "point_of_interest", "establishment"],
        "displayName": "Bondi Beach",
        "googleMapsUri": "https://maps.google.com/?cid=3358451087598589142",
        "primaryType": "beach",
        "primaryTypeDisplayName": "Beach",
        "subDestinations": None,
        "rating": 4.6,
        "userRatingCount": 24000,
        "websiteUri": None,
        "parkingOptions": {"selfParkingAvailable": True, "valetParkingAvailable": False},
        "paymentOptions": None,
        "outdoorSeating": True,
        "reservable": False,
        "reviews": [
            {"authorAttribution": {"displayName": "Beach Lover"}, "text": "Beautiful beach with great waves!", "rating": 5},
            {"authorAttribution": {"displayName": "Surfer Dude"}, "text": "Perfect spot for surfing.", "rating": 5}
        ]
    },
    {
        "id": "4",
        "addressComponents": [
            {"long_name": "Sydney Harbour Bridge", "short_name": "Sydney Harbour Bridge", "types": ["route"]},
            {"long_name": "Sydney", "short_name": "Sydney", "types": ["locality", "political"]},
            {"long_name": "Council of the City of Sydney", "short_name": "Sydney", "types": ["administrative_area_level_2", "political"]},
            {"long_name": "New South Wales", "short_name": "NSW", "types": ["administrative_area_level_1", "political"]},
            {"long_name": "Australia", "short_name": "AU", "types": ["country", "political"]},
            {"long_name": "2000", "short_name": "2000", "types": ["postal_code"]}
        ],
        "adrFormatAddress": "Sydney Harbour Bridge, Sydney NSW 2000, Australia",
        "formattedAddress": "Sydney Harbour Bridge, Sydney NSW 2000, Australia",
        "location": {"latitude": -33.8523063, "longitude": 151.2107871},
        "plusCode": "4RRJ+3C Sydney, New South Wales",
        "shortFormattedAddress": "Sydney Harbour Bridge, Sydney NSW",
        "types": ["tourist_attraction", "point_of_interest", "establishment"],
        "displayName": "Sydney Harbour Bridge",
        "googleMapsUri": "https://maps.google.com/?cid=11747831013099866138",
        "primaryType": "tourist_attraction",
        "primaryTypeDisplayName": "Tourist Attraction",
        "subDestinations": None,
        "rating": 4.8,
        "userRatingCount": 46000,
        "websiteUri": "https://www.bridgeclimb.com/",
        "parkingOptions": None,
        "paymentOptions": None,
        "outdoorSeating": False,
        "reservable": True,
        "reviews": None
    },
    {
        "id": "5",
        "addressComponents": [
            {"long_name": "1", "short_name": "1", "types": ["street_number"]},
            {"long_name": "Darling Drive", "short_name": "Darling Dr", "types": ["route"]},
            {"long_name": "Sydney", "short_name": "Sydney", "types": ["locality", "political"]},
            {"long_name": "Council of the City of Sydney", "short_name": "Sydney", "types": ["administrative_area_level_2", "political"]},
            {"long_name": "New South Wales", "short_name": "NSW", "types": ["administrative_area_level_1", "political"]},
            {"long_name": "Australia", "short_name": "AU", "types": ["country", "political"]},
            {"long_name": "2000", "short_name": "2000", "types": ["postal_code"]}
        ],
        "adrFormatAddress": "1 Darling Dr, Sydney NSW 2000, Australia",
        "formattedAddress": "1 Darling Dr, Sydney NSW 2000, Australia",
        "location": {"latitude": -33.8743537, "longitude": 151.1985886},
        "plusCode": "4RRF+7C Sydney, New South Wales",
        "shortFormattedAddress": "1 Darling Dr, Sydney NSW",
        "types": ["aquarium", "tourist_attraction", "point_of_interest", "establishment"],
        "displayName": "SEA LIFE Sydney Aquarium",
        "googleMapsUri": "https://maps.google.com/?cid=3298246352216313425",
        "primaryType": "aquarium",
        "primaryTypeDisplayName": "Aquarium",
        "subDestinations": None,
        "rating": 4.3,
        "userRatingCount": 30000,
        "websiteUri": "https://www.sydneyaquarium.com.au/",
        "parkingOptions": {"selfParkingAvailable": True, "valetParkingAvailable": False},
        "paymentOptions": {"acceptsCreditCards": True, "acceptsDebitCards": True, "acceptsCash": True},
        "outdoorSeating": False,
        "reservable": True,
        "reviews": [
            {"authorAttribution": {"displayName": "Marine Enthusiast"}, "text": "Great variety of sea life!", "rating": 4},
            {"authorAttribution": {"displayName": "Family Traveler"}, "text": "Kids loved it, but a bit crowded.", "rating": 4}
        ]
    },
    {
        "id": "6",
        "addressComponents": [
            {"long_name": "100", "short_name": "100", "types": ["street_number"]},
            {"long_name": "Cumberland Street", "short_name": "Cumberland St", "types": ["route"]},
            {"long_name": "The Rocks", "short_name": "The Rocks", "types": ["locality", "political"]},
            {"long_name": "Council of the City of Sydney", "short_name": "Sydney", "types": ["administrative_area_level_2", "political"]},
            {"long_name": "New South Wales", "short_name": "NSW", "types": ["administrative_area_level_1", "political"]},
            {"long_name": "Australia", "short_name": "AU", "types": ["country", "political"]},
            {"long_name": "2000", "short_name": "2000", "types": ["postal_code"]}
        ],
        "adrFormatAddress": "100 Cumberland St, The Rocks NSW 2000, Australia",
        "formattedAddress": "100 Cumberland St, The Rocks NSW 2000, Australia",
        "location": {"latitude": -33.8567844, "longitude": 151.2092668},
        "plusCode": "4RRH+H4 The Rocks, New South Wales",
        "shortFormattedAddress": "100 Cumberland St, The Rocks NSW",
        "types": ["tourist_attraction", "point_of_interest", "establishment"],
        "displayName": "Sydney Harbour Bridge Pylon Lookout",
        "googleMapsUri": "https://maps.google.com/?cid=780073953044631923",
        "primaryType": "tourist_attraction",
        "primaryTypeDisplayName": "Tourist Attraction",
        "subDestinations": None,
        "rating": 4.6,
        "userRatingCount": 3000,
        "websiteUri": "https://pylonlookout.com.au/",
        "parkingOptions": None,
        "paymentOptions": {"acceptsCreditCards": True, "acceptsDebitCards": True, "acceptsCash": True},
        "outdoorSeating": False,
        "reservable": False,
        "reviews": None
    },
    {
        "id": "7",
        "addressComponents": [
            {"long_name": "1", "short_name": "1", "types": ["street_number"]},
            {"long_name": "Artillery Drive", "short_name": "Artillery Dr", "types": ["route"]},
            {"long_name": "Mosman", "short_name": "Mosman", "types": ["locality", "political"]},
            {"long_name": "Mosman Council", "short_name": "Mosman", "types": ["administrative_area_level_2", "political"]},
            {"long_name": "New South Wales", "short_name": "NSW", "types": ["administrative_area_level_1", "political"]},
            {"long_name": "Australia", "short_name": "AU", "types": ["country", "political"]},
            {"long_name": "2088", "short_name": "2088", "types": ["postal_code"]}
        ],
        "adrFormatAddress": "1 Artillery Dr, Mosman NSW 2088, Australia",
        "formattedAddress": "1 Artillery Dr, Mosman NSW 2088, Australia",
        "location": {"latitude": -33.8431651, "longitude": 151.2428639},
        "plusCode": "4RRQ+PV Mosman, New South Wales",
        "shortFormattedAddress": "1 Artillery Dr, Mosman NSW",
        "types": ["zoo", "tourist_attraction", "point_of_interest", "establishment"],
        "displayName": "Taronga Zoo Sydney",
        "googleMapsUri": "https://maps.google.com/?cid=6521584471322710094",
        "primaryType": "zoo",
        "primaryTypeDisplayName": "Zoo",
        "subDestinations": None,
        "rating": 4.5,
        "userRatingCount": 25000,
        "websiteUri": "https://taronga.org.au/sydney-zoo",
        "parkingOptions": {"selfParkingAvailable": True, "valetParkingAvailable": False},
        "paymentOptions": {"acceptsCreditCards": True, "acceptsDebitCards": True, "acceptsCash": True},
        "outdoorSeating": True,
        "reservable": True,
        "reviews": [
            {"authorAttribution": {"displayName": "Animal Lover"}, "text": "Amazing variety of animals and great views of Sydney!", "rating": 5},
            {"authorAttribution": {"displayName": "Family Day Out"}, "text": "Excellent day out for the family. The kids loved it!", "rating": 4}
        ]
    },
    {
        "id": "8",
        "addressComponents": [
            {"long_name": "Art Gallery Road", "short_name": "Art Gallery Rd", "types": ["route"]},
            {"long_name": "Sydney", "short_name": "Sydney", "types": ["locality", "political"]},
            {"long_name": "Council of the City of Sydney", "short_name": "Sydney", "types": ["administrative_area_level_2", "political"]},
            {"long_name": "New South Wales", "short_name": "NSW", "types": ["administrative_area_level_1", "political"]},
            {"long_name": "Australia", "short_name": "AU", "types": ["country", "political"]},
            {"long_name": "2000", "short_name": "2000", "types": ["postal_code"]}
        ],
        "adrFormatAddress": "Art Gallery Rd, Sydney NSW 2000, Australia",
        "formattedAddress": "Art Gallery Rd, Sydney NSW 2000, Australia",
        "location": {"latitude": -33.8686685, "longitude": 151.2172006},
        "plusCode": "4RRH+GV Sydney, New South Wales",
        "shortFormattedAddress": "Art Gallery Rd, Sydney NSW",
        "types": ["art_gallery", "tourist_attraction", "point_of_interest", "establishment"],
        "displayName": "Art Gallery of New South Wales",
        "googleMapsUri": "https://maps.google.com/?cid=13284067721269169340",
        "primaryType": "art_gallery",
        "primaryTypeDisplayName": "Art Gallery",
        "subDestinations": None,
        "rating": 4.6,
        "userRatingCount": 10000,
        "websiteUri": "https://www.artgallery.nsw.gov.au/",
        "parkingOptions": {"selfParkingAvailable": True, "valetParkingAvailable": False},
        "paymentOptions": {"acceptsCreditCards": True, "acceptsDebitCards": True, "acceptsCash": True},
        "outdoorSeating": False,
        "reservable": False,
        "reviews": None
    },
    {
        "id": "9",
        "addressComponents": [
            {"long_name": "Mrs Macquaries Road", "short_name": "Mrs Macquaries Rd", "types": ["route"]},
            {"long_name": "Sydney", "short_name": "Sydney", "types": ["locality", "political"]},
            {"long_name": "Council of the City of Sydney", "short_name": "Sydney", "types": ["administrative_area_level_2", "political"]},
            {"long_name": "New South Wales", "short_name": "NSW", "types": ["administrative_area_level_1", "political"]},
            {"long_name": "Australia", "short_name": "AU", "types": ["country", "political"]},
            {"long_name": "2000", "short_name": "2000", "types": ["postal_code"]}
        ],
        "adrFormatAddress": "Mrs Macquaries Rd, Sydney NSW 2000, Australia",
        "formattedAddress": "Mrs Macquaries Rd, Sydney NSW 2000, Australia",
        "location": {"latitude": -33.8641958, "longitude": 151.2166455},
        "plusCode": "4RRH+8M Sydney, New South Wales",
        "shortFormattedAddress": "Mrs Macquaries Rd, Sydney NSW",
        "types": ["park", "tourist_attraction", "point_of_interest", "establishment"],
        "displayName": "Royal Botanic Garden Sydney",
        "googleMapsUri": "https://maps.google.com/?cid=7228954494072562518",
        "primaryType": "park",
        "primaryTypeDisplayName": "Park",
        "subDestinations": None,
        "rating": 4.7,
        "userRatingCount": 35000,
        "websiteUri": "https://www.rbgsyd.nsw.gov.au/",
        "parkingOptions": {"selfParkingAvailable": True, "valetParkingAvailable": False},
        "paymentOptions": None,
        "outdoorSeating": True,
        "reservable": False,
        "reviews": [
            {"authorAttribution": {"displayName": "Nature Enthusiast"}, "text": "Beautiful gardens with a stunning harbor view!", "rating": 5},
            {"authorAttribution": {"displayName": "Tourist"}, "text": "Perfect place for a picnic and relaxation.", "rating": 5}
        ]
    },
    {
        "id": "10",
        "addressComponents": [
            {"long_name": "Campbell Parade", "short_name": "Campbell Parade", "types": ["route"]},
            {"long_name": "Bondi Beach", "short_name": "Bondi Beach", "types": ["locality", "political"]},
            {"long_name": "Waverley Council", "short_name": "Waverley", "types": ["administrative_area_level_2", "political"]},
            {"long_name": "New South Wales", "short_name": "NSW", "types": ["administrative_area_level_1", "political"]},
            {"long_name": "Australia", "short_name": "AU", "types": ["country", "political"]},
            {"long_name": "2026", "short_name": "2026", "types": ["postal_code"]}
        ],
        "adrFormatAddress": "Campbell Parade, Bondi Beach NSW 2026, Australia",
        "formattedAddress": "Campbell Parade, Bondi Beach NSW 2026, Australia",
        "location": {"latitude": -33.8915755, "longitude": 151.2766845},
        "plusCode": "4R6R+9M Bondi Beach, New South Wales",
        "shortFormattedAddress": "Campbell Parade, Bondi Beach NSW",
        "types": ["neighborhood", "political"],
        "displayName": "Bondi Beach",
        "googleMapsUri": "https://maps.google.com/?cid=5743789441073035206",
        "primaryType": "neighborhood",
        "primaryTypeDisplayName": "Neighborhood",
        "subDestinations": None,
        "rating": None,
        "userRatingCount": None,
        "websiteUri": None,
        "parkingOptions": None,
        "paymentOptions": None,
        "outdoorSeating": None,
        "reservable": False,
        "reviews": None
    }
]